
language: python
python:
    - "3.5"

install:
    - python -m pip install -r requirements.dev.txt
    - nvm install 0.11.12
    - npm install -g npm@1.4.8
    - npm install -g https://github.com/wk0206/xml2csv.git

script:
    - coverage run --source os_fdp_adapters -m pytest 

after_success:
    - coveralls

