
language: python
python:
    - "3.5"

install:
    - python -m pip install -r requirements.dev.txt
    - nvm install 0.10
    - export PATH=$PWD:$PATH
    - npm install -g https://github.com/wk0206/xml2csv.git
    - npm config get prefix

script:
    - coverage run --source os_fdp_adapters -m pytest 

after_success:
    - coveralls

