
language: python
python:
    - "2.7"

before_install:
    - sudo apt-get install g++ build-essential

install:
    - python -m pip install -r requirements.dev.txt
    - nvm install 5.12.0
    - npm install -g node-gyp
    - npm install -g https://github.com/wk0206/xml2csv.git

script:
    - coverage run --source os_fdp_adapters -m pytest 

after_success:
    - coveralls

